name: archetypal
channels:
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - conda-forge
dependencies:
  - osmnx>=0.9
  - lxml
  - shapely
  - geopandas>=0.3
  - matplotlib>=2.1
  - requests>=2.18
  - pycountry
  - scikit-learn
  - pandas>=0.21
  - numpy>=1.13
  - tqdm
  - pip:
    - eppy
    - geomeppy
    - pyomo
    - utm