name: archetypal
channels:
  - defaults
dependencies:
  - lxml
  - shapely
  - matplotlib>=2.1
  - requests>=2.18
  - pycountry
  - scipy
  - scikit-learn
  - pandas>=0.21
  - numpy>=1.13
  - tqdm
  - pip:
    - eppy
    - geomeppy
    - pyomo
    - utm